# Generated by Django 4.2.7 on 2024-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0021_foodmenu_rename_driver_booking_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idnumber',
            field=models.IntegerField(default='1'),
        ),
    ]
